"""empty message

Revision ID: 45a396217a87
Revises: None
Create Date: 2016-07-12 02:31:28.729046

"""

# revision identifiers, used by Alembic.
revision = '45a396217a87'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('text_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texters')
    ### end Alembic commands ###
